# Use uma imagem base mínima com um servidor HTTP
FROM nginx:alpine

# Copie o arquivo index.html para a pasta padrão do NGINX
COPY index.html /usr/share/nginx/html/index.html

# Exponha a porta padrão usada pelo NGINX
EXPOSE 5000

# Inicie o servidor NGINX
CMD ["nginx", "-g", "daemon off;"]